<?php

namespace TechCorp\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{
    public function getStatus()
    {
        //return $this->_em->createQuery('SELECT s FROM TechCorpFrontBundle:Status s');
     
        return $this->_em->createQuery('SELECT s,u FROM TechCorpFrontBundle:Status s 
                                        JOIN s.user u ORDER BY s.createdAt DESC');
    }
    
    public function getUserTimeline($user)
    {
        return $this->_em->createQuery('SELECT s FROM TechCorpFrontBundle:Status s 
                                        WHERE s.user = :user')->setParameter('user', $user);
    }
    
    
    public function getFriendsTimeline($user)
    {
        return $this->_em->createQuery('SELECT s FROM TechCorpFrontBundle:Status s
                                        WHERE s.user in (SELECT friends from TechCorpFrontBundle:User uf JOIN uf.friends 
                                        friends where uf=:user) ORDER BY s.createdAt DESC')->setParameter('user', $user);
    }
    
    
}
